# Generated by Django 5.0.6 on 2026-09-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('FOOD', 'Food & Dining'), ('TRAVEL', 'Travel'), ('RENT', 'Rent'), ('UTILITIES', 'Utilities'), ('EDUCATION', 'Education'), ('SHOPPING', 'Shopping'), ('ENTERTAINMENT', 'Entertainment'), ('HEALTH', 'Health'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('NET_BANKING', 'Net Banking')], default='UPI', max_length=20)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
